# Dockerfile.prod
FROM node:18-alpine AS builder

WORKDIR /app

COPY frontend-app/package*.json ./
RUN npm install

COPY frontend-app ./
RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY ./nginx/nginx-certs /etc/nginx/certs
COPY ./nginx/nginx.prod.conf /etc/nginx/nginx.conf
