services:
  backend-app:
    image: ${BACKEND_IMAGE}
    build:
      context: ./backend-app
      dockerfile: Dockerfile

  frontend-app:
    image: ${FRONTEND_IMAGE}
    build:
      context: ./frontend-app
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend-app:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/nginx-certs:/etc/nginx/certs:ro
    depends_on:
      - frontend-app
      - backend-app
    networks:
      - app-network
