services:
  backend-app:
    image: ${BACKEND_IMAGE}
    build:
      context: ./backend-app
      dockerfile: Dockerfile
      target: final
    environment:
      - PORT=${BACKEND_PORT}
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
