services:
  nginx:
    image: ${FRONTEND_IMAGE}
    build:
      context: .
      dockerfile: frontend-app/Dockerfile.prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx-certs:/etc/nginx/certs:ro
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend-app
    networks:
      - app-network
