services:
  nginx:
    image: ${FRONTEND_IMAGE}
    build:
      context: .
      dockerfile: frontend-app/Dockerfile.prod
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend-app
    networks:
      - app-network
