[package]
name = "backend-app"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.1" }
hyper = { version = "1.6.0", features = ["full"] }
tokio = { version = "1.44.1", features = ["full"] }
tower = "0.5.2"
