name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create .env.prod file
        run: |
          echo "BACKEND_PORT=5000" >> .env.prod
          echo "ENVIRONMENT=production" >> .env.prod
          echo "FRONTEND_IMAGE=ghcr.io/Shawn-Armstrong/frontend-app:latest" >> .env.prod
          echo "BACKEND_IMAGE=ghcr.io/Shawn-Armstrong/backend-app:latest" >> .env.prod

      - name: Build and push images using Docker Compose
        run: |
          docker compose --env-file .env.prod -f compose.yaml -f compose.prod.yaml build
          docker compose --env-file .env.prod -f compose.yaml -f compose.prod.yaml push

      # - name: Deploy to DigitalOcean via SSH
      #   uses: appleboy/ssh-action@v1.0.3
      #   with:
      #     host: ${{ secrets.DO_HOST }}
      #     username: ${{ secrets.DO_USER }}
      #     key: ${{ secrets.DO_SSH_KEY }}
      #     script: |
      #       cd ucsc-network || exit 1
      #       git pull origin main
      #       docker compose --env-file .env.prod -f compose.yaml -f compose.prod.yaml pull
      #       docker compose --env-file .env.prod -f compose.yaml -f compose.prod.yaml up -d
