name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create .env.prod file
        run: |
          echo "BACKEND_PORT=5000" >> .env.prod
          echo "ENVIRONMENT=production" >> .env.prod
          echo "FRONTEND_IMAGE=ghcr.io/shawn-armstrong/frontend-app:latest" >> .env.prod
          echo "BACKEND_IMAGE=ghcr.io/shawn-armstrong/backend-app:latest" >> .env.prod

      # Debug: List workspace contents
      - name: Debug List workspace contents
        run: ls -al

      - name: Debug Print Working Directory
        run: pwd

      - name: Create Remote Directory
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: mkdir -p /root/ucsc-network
          
      - name: Debug List entire directory recursively using find
        run: find .
      
      - name: Install tree (for better visual output)
        run: sudo apt-get update && sudo apt-get install -y tree
      
      - name: Debug Print directory tree
        run: tree -a -i ".git"

      - name: Show home directory
        run: |
          echo "Home directory is: ~ -> $(echo ~)"
          ls -al ~

      - name: Upload Compose files to Droplet
        uses: appleboy/scp-action@v0.1.4
        with:
          host:  ${{ secrets.DROPLET_IP }}
          username: root
          key: ${{ secrets.DROPLET_SSH_KEY }}
          debug: true
          source: "compose.yaml compose.prod.yaml .env.prod"
          target: "/root/ucsc-network"

      - name: Deploy to DigitalOcean via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            cd /root/ucsc-network || exit 1
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
            docker compose --env-file .env.prod -f compose.yaml -f compose.prod.yaml pull
            docker compose --env-file .env.prod -f compose.yaml -f compose.prod.yaml up -d
