name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create .env.prod file
        run: |
          echo "BACKEND_PORT=5000" >> .env.prod
          echo "ENVIRONMENT=production" >> .env.prod
          echo "FRONTEND_IMAGE=ghcr.io/shawn-armstrong/frontend-app:latest" >> .env.prod
          echo "BACKEND_IMAGE=ghcr.io/shawn-armstrong/backend-app:latest" >> .env.prod

      - name: Build and push images using Docker Compose
        run: |
          docker compose --env-file .env.prod -f compose.yaml -f compose.prod.yaml build
          docker compose --env-file .env.prod -f compose.yaml -f compose.prod.yaml push

      - name: Upload Compose files to droplet
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          source: "compose.yaml,compose.prod.yaml,.env.prod"
          target: "~/ucsc-deploy"

      - name: Deploy to DigitalOcean via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            cd ~/ucsc-deploy
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
            docker compose --env-file .env.prod -f compose.yaml -f compose.prod.yaml pull
            docker compose --env-file .env.prod -f compose.yaml -f compose.prod.yaml up -d
